# Apply tu RUN cluster(s)
apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  labels:
    app.kubernetes.io/component: deliverable
    app.kubernetes.io/part-of: tanzu-java-web-app
    app.tanzu.vmware.com/deliverable-type: web
    carto.run/workload-name: tanzu-java-web-app
    carto.run/workload-namespace: demo-apps
  name: tanzu-java-web-app
  namespace: demo-apps
spec:
  source:
    git:
      ref:
        branch: main
      url: https://github.com/ciberkleid-tap/tap-workload-gitops.git
    subPath: config/demo-apps/tanzu-java-web-app